// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP8eLyXri0JWqscu6StidrJKOl4ww_v_E',
    appId: '1:433408603663:web:87cb1afe6619d74785957a',
    messagingSenderId: '433408603663',
    projectId: 'rides-n-bikes-app-a9cde',
    authDomain: 'rides-n-bikes-app-a9cde.firebaseapp.com',
    storageBucket: 'rides-n-bikes-app-a9cde.appspot.com',
    measurementId: 'G-F3FPZEXT46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5_GseqF0gKr6E3JokbW5tFRWYzeGMfdc',
    appId: '1:433408603663:android:2d0b18bd3077d6a785957a',
    messagingSenderId: '433408603663',
    projectId: 'rides-n-bikes-app-a9cde',
    storageBucket: 'rides-n-bikes-app-a9cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD4_YsibOeABhl-lWCck5TFrTVySbqPMA',
    appId: '1:433408603663:ios:ad7e333dd2c7502d85957a',
    messagingSenderId: '433408603663',
    projectId: 'rides-n-bikes-app-a9cde',
    storageBucket: 'rides-n-bikes-app-a9cde.appspot.com',
    iosBundleId: 'com.example.ridesNBikes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD4_YsibOeABhl-lWCck5TFrTVySbqPMA',
    appId: '1:433408603663:ios:6116a6a13ba93a2285957a',
    messagingSenderId: '433408603663',
    projectId: 'rides-n-bikes-app-a9cde',
    storageBucket: 'rides-n-bikes-app-a9cde.appspot.com',
    iosBundleId: 'com.example.ridesNBikes.RunnerTests',
  );
}
